spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:mysql://localhost:3306/pms_users_db;
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: none  # Disable Hibernate's automatic DDL to let Flyway manage the schema
    show-sql: true
  flyway:
    locations: classpath:db/migration  # Location of migration scripts
    enabled: true
    baseline-on-migrate: true


eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Change the default port
server:
  port: 8071

