eureka:
  client:
    register-with-eureka: false

server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: attendance-service
          uri: http://localhost:8070
          predicates:
            - Path=/api/v1/users/**
        - id: auth-service
          uri: http://localhost:8071
          predicates:
            - Path=/api/v1/posts/**
        - id: config-service
          uri: http://localhost:8072
          predicates:
            - Path=/api/v1/comments/**
        - id: employee-service
          uri: http://localhost:8073
          predicates:
            - Path=/api/v1/status/**
        - id: payroll-service
          uri: http://localhost:8074
          predicates:
            - Path=/api/v1/status/**
        - id: project-service
          uri: http://localhost:8075
          predicates:
            - Path=/api/v1/status/**
        - id: supplier-service
          uri: http://localhost:8076
          predicates:
            - Path=/api/v1/status/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true